name: CI/CD Jobs
on:
  push:
    # branches:
    #   - main
    #   - develop
  workflow_dispatch:

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Pull in content repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.CONTENT_REPO }}
          token: ${{ secrets.GH_PAT }}
          path: src/content
          fetch-depth: 0

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Pull down all drafts
        if: github.ref != 'refs/heads/main'
        run: ./.github/scripts/flatten_branches.sh
        shell: bash

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Generate site
        run: |
          npm install
          npm run build

      - name: Save dev bucket name
        if: github.ref != 'refs/heads/main'
        run: echo "BUCKET=${{ secrets.DEV_BUCKET }}" >> $GITHUB_ENV

      - name: Save prod bucket name
        if: github.ref == 'refs/heads/main'
        run: echo "BUCKET=${{ secrets.PROD_BUCKET }}" >> $GITHUB_ENV

      - name: Upload to object storage
        uses: BetaHuhn/do-spaces-action@master
        with:
          access_key: ${{ secrets.ACCESS_ID }}
          secret_key: ${{ secrets.SECRET_KEY }}
          space_region: ${{ secrets.REGION }}
          space_name: $BUCKET
          source: dist
          permission: private
