name: Build Site
on:
  push:
    branches:
      - main
      - develop
jobs:
  trigger-build:
    name: Trigger site build
    runs-on: ubuntu-latest
    steps:
      - name: Send Workflow Dispatch API request
        run: >
          curl -X POST -i -H "Authorization: token ${{ secrets.GH_PAT }}"
          -H "Content-Type: application/json" -H "Accept: application/vnd.github.v3+json"
          -d '{"ref": "main", "inputs": {"branch": "${{ github.ref }}"}}'
          https://api.github.com/repos/kilbd/${{ secrets.CONTENT_REPO }}/actions/workflows/main.yaml/dispatches
